### ISSUE TITLE
Roadmap Board

### ISSUE THREAD

**Issue by elgirafo** [windingtree/roadmap#3]
- [ ] get the [Roadmap project board](https://github.com/orgs/windingtree/projects/23/views/1) up to date
- [ ] make sure all issues in [windingtree/roadmap](https://github.com/windingtree/roadmap/issues) repository are tracked on the Roadmap project board
- [ ] make sure all action items from the Roadmap have a decent description
